import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import NextUIProvider from '@/components/NextUIProvider';
import { ApolloClientProvider } from '@/graphql';
import { cn } from '@/utils';

import './tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  readonly children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-dvh')}>
        <ApolloClientProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
